### ISSUE TITLE
转换音色不是很相似

### ISSUE THREAD

**Issue by xiangkanghuang** [nilboy/vc-lm#1]
![image](https://github.com/nilboy/vc-lm/assets/20598757/e6b3d4a3-d172-4f4e-bf7e-df953e3501ca)
readme中准换模型写的是small模型，配置文件写的是medium文件？
改成medium的whisper模型，跑通了，但音色并没有很像，是哪里出问题了吗

**Comment by nilboy** [comment]
这个模型最终的效果，并不能作为Any to Any的变声器来使用，存在音色不像的问题，可能有两种方案来做Any to one的变声:
1. 基于这个模型，在特定人数据上面继续finetune, (10分钟的数据可以到不错的效果)。但是vc-lm模型太大，推理速度比较慢。
2. 该模型可以生成大量one-to-any的平行数据(也就是any-to-one)。这些平行数据可以被用来训练 其他Any-to-One 的变声模型。

**Comment by nilboy** [comment]
新增功能: 支持Any to One 声音转换模型训练，[any-to-one](https://github.com/nilboy/vc-lm/commit/79a6e370df0fc245006a4597a029ea0a2084157c)
