### ISSUE TITLE
请问我们项目可以实现这个视频的效果吗？（将一个人的语音翻译任意语言，然后再基于这个人的 音色将译文读出来）

### ISSUE THREAD

**Issue by zhanghongyong123456** [nilboy/vc-lm#2]
首先感谢大佬的新颖项目，感觉很有趣，我们项目可以实现这个视频中展示的这个效果吗，如果不能的话，有没有相关的项目可以实现的，求推荐？谢谢大佬
https://www.bilibili.com/video/BV1xX4y1h7Jd/?spm_id_from=333.788&vd_source=b60327c7d66c2b251b37920822c38f4e

**Comment by nilboy** [comment]
这个项目不支持。
您上面那个例子涉及到语音识别，机器翻译，语音合成(小样本TTS)，2D数字人口型合成等多个算法模块。
每个模块都有一些开源的实现的，现成的把所有模块组合在一起的开源项目我还没看到

**Comment by zhanghongyong123456** [comment]
> 这个项目不支持。 您上面那个例子涉及到语音识别，机器翻译，语音合成(小样本TTS)，2D数字人口型合成等多个算法模块。 每个模块都有一些开源的实现的，现成的把所有模块组合在一起的开源项目我还没看到

那请问转换成的新语言，读出来时候添加输入人的音色，这个有哪些项目（就像中文输入，最后输出英文时候带有一些中文输入人的音色）

**Comment by zhanghongyong123456** [comment]
> 这个项目不支持。 您上面那个例子涉及到语音识别，机器翻译，语音合成(小样本TTS)，2D数字人口型合成等多个算法模块。 每个模块都有一些开源的实现的，现成的把所有模块组合在一起的开源项目我还没看到

请问，如何保存成音频：我查看输出是 numpy格式数据。
![image](https://github.com/nilboy/vc-lm/assets/48466610/a4861cda-bf59-45b2-8510-e8615fff67fc)
